# Generated by Django 4.2.3 on 2023-07-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_alter_quiz_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswers',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
