# Generated by Django 4.2.3 on 2023-07-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0003_alter_quizanswers_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
