# Generated by Django 4.2.3 on 2023-07-20 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0007_quizresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresponse',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_responses', to='QuizApp.quiz'),
        ),
    ]
